version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: receptboken_db
    environment:
      POSTGRES_DB: receptboken
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d receptboken"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: